#docker compose file formate version
version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: polling_app_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: polling_app_backend
    ports:
      - "5001:5001"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=polldb

    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: polling_app_db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=polldb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

